DELETE FROM STUDENT WHERE ID IN (SELECT DISTINCT M.STUDENT_ID FROM MARK M JOIN SUBJECT S on M.SUBJECT_ID = S.ID  WHERE S.GRADE>=4);
DELETE FROM STUDENT WHERE ID IN (SELECT DISTINCT S.ID FROM STUDENT S JOIN MARK M ON S.ID = M.STUDENT_ID WHERE M.MARK<4);
DELETE FROM PAYMENTTYPE WHERE NAME='DAILY';
DELETE FROM MARK WHERE MARK<7;