DELETE FROM STUDENT WHERE ID IN(SELECT MARK.STUDENT_ID FROM MARK WHERE MARK.SUBJECT_ID IN (SELECT SUBJECT.ID FROM SUBJECT WHERE SUBJECT.GRADE>=4));
DELETE FROM STUDENT WHERE ID IN (SELECT MARK.STUDENT_ID FROM MARK WHERE MARK.MARK<4);
DELETE FROM PAYMENT WHERE ID IN (SELECT PAYMENTTYPE.ID FROM PAYMENTTYPE WHERE PAYMENTTYPE.NAME='DAILY');
DELETE FROM MARK WHERE MARK.MARK<7;

