SELECT * FROM MARK where mark > 6 ORDER BY mark DESC;
SELECT * FROM PAYMENT where amount<300 ORDER BY amount ASC;
SELECT * FROM PAYMENTTYPE ORDER BY NAME ASC;
SELECT * FROM STUDENT ORDER BY name DESC;
SELECT * FROM STUDENT LEFT JOIN PAYMENT ON STUDENT.id = PAYMENT.STUDENT_ID WHERE PAYMENT.AMOUNT>1000 ORDER BY BIRTHDAY ASC;

