SELECT * FROM Payment WHERE amount >=500;
SELECT * FROM STUDENT WHERE BIRTHDAY <  dateadd(year, -20, CURDATE());
SELECT * FROM STUDENT WHERE BIRTHDAY >  dateadd(year, -20, CURDATE());
//SELECT * FROM STUDENT WHERE ((name LIKE 'Mike%') OR (GROUPNUMBER = 4) OR (GROUPNUMBER = 5) OR (GROUPNUMBER = 6));
SELECT * FROM STUDENT WHERE name LIKE 'Mike%' OR GROUPNUMBER IN (4,5,6);
SELECT * FROM Payment WHERE PAYMENT_DATE > dateadd(month, -8, CURDATE());
SELECT * FROM STUDENT WHERE name LIKE 'A%';
SELECT * FROM STUDENT WHERE (name LIKE 'Roxi%' and GROUPNUMBER =4) or (name LIKE 'Tallie%' and GROUPNUMBER =9) ;
