ALTER TABLE STUDENT ALTER COLUMN BIRTHDAY SET NOT NULL;
ALTER TABLE MARK ALTER COLUMN student_id SET NOT NULL;
ALTER TABLE MARK ALTER COLUMN subject_id SET NOT NULL;
ALTER TABLE MARK ADD CONSTRAINT mark3 CHECK (mark <= 10);
ALTER TABLE MARK ADD CONSTRAINT mark2 CHECK (mark > 0);
ALTER TABLE SUBJECT ADD CONSTRAINT grade3 CHECK (grade <= 5);
ALTER TABLE SUBJECT ADD CONSTRAINT grade2 CHECK (grade > 0);
ALTER TABLE PAYMENTTYPE ADD CONSTRAINT "name" UNIQUE(NAME);
ALTER TABLE PAYMENT ALTER COLUMN type_id SET NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN amount SET NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN payment_date SET NOT NULL;

